#@HeroApi_HostAddress = https://localhost:7227/Hero
@HeroApi_HostAddress = https://localhost:5002/Hero

GET {{HeroApi_HostAddress}}/
Accept: application/json

###

GET {{HeroApi_HostAddress}}/2
Accept: application/json

###


POST {{HeroApi_HostAddress}}/
Content-Type: application/json
Accept: application/json

{
  "name": "John",
  "superPower":"learning"
}

###

PUT {{HeroApi_HostAddress}}/1
Content-Type: application/json
Accept: application/json

{
  "name": "Iwan",
  "superPower":"beer"
}

###

DELETE {{HeroApi_HostAddress}}/1
Content-Type: application/json