version: '3.8'

networks:
  metrics:
    name: hero-network
    
services:
  # prometheus:
  #   build: 
  #     context: ./scripts/prometheus
  #   depends_on:
  #     - app
  #   ports:
  #     - 9090:9090
  #   networks:
  #     - metrics

  # grafana:
  #   build: 
  #     context: ./scripts/grafana
  #   depends_on:
  #     - prometheus
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - metrics
  
  otel-collector:
    image: otel/opentelemetry-collector:0.89.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./scripts/otel-collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888" 
      - "8889:8889" 
      - "13133:13133"
      - "4317:4317"
    networks:
      - metrics

  app:
    build:
      context: ./
      dockerfile: ./HeroApi/Dockerfile
    depends_on:
      - otel-collector
    ports:
      - 5001:8080
      - 5002:8088
    environment:
      - Otlp__Endpoint=http://otel-collector:4317
      # - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Kestrel__Certificates__Default__Password=secret
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/heroapi.pfx
    volumes:
      - ./https:/https:ro
    networks:
      - metrics