{
 "title": "Hero dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Heros!",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Number of Books Available in the Store",
     "type": "stat",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "total-Hero_HEro", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Books Added",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "hero_added_Hero_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heros died",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 9, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "hero_deleted_Hero_total", "legendFormat": "__auto" }
     ]
    },
    {
     "title": "Heros Updated",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 13, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      { "expr": "hero_updated_Hero_total", "legendFormat": "__auto" }
     ]
    }
   ]
  }
 ]
}